### ISSUE TITLE
@image fails with file names including spaces

### ISSUE THREAD

**Issue by vejazi** [pasdoc/pasdoc#107]
The image tag does not work properly with filnames containing spaces. All following lines but the first (of course) produce an error while processing the documentation or an empty image file in the destination folder.

    ///  @image(..\docs\File_Name.png)
    ///  @image("..\docs\File Name.png")
    ///  @image('..\docs\File Name.png')
    ///  @image(´..\docs\File Name.png´)
    ///  @image(`..\docs\File Name.png`)

Not sure if this is sufficient information. I'll be happy to assist if necessary.

  Veit

**Comment by Fr0sT-Brutal** [comment]
Actually this is not allowed by HTML: [SO](https://stackoverflow.com/questions/4172579/href-syntax-is-it-okay-to-have-space-in-file-name)

Nevertheless PasDoc should allow it for local outputs f.ex.
In addition: [docs](https://github.com/pasdoc/pasdoc/wiki/ImageTag) say multiple paths are separated with newlines but examples show spaces.

**Comment by vejazi** [comment]
I agree that there needs to be some quoting, but maybe I wasn't precise enough:

1. The file is copied to the destination folder AND renamed to "image_9.png" by pasdoc. Probably because of HTML rules.
2. I only have one image file. Documentation talks about several file types of the same image.
3. I tried only one of the lines per test.
4. A path in general works, but I didn't have any spaces in the path (see 1.).

So overall the problem must be somewhere in processing as it either fails to parse it properly (error while processing/parsing) or the image file in the destination folder is zero bytes in size. Not sure when that happens.

**Comment by michaliskambi** [comment]
Just don't use any quotes :) This should work OK:

```pascal
//  @image(..\docs\File Name.png)
```

I just confirmed it, this works OK:

```pascal
{ Sample image with spaces: @image(something something with spaces.png) }
unit a;
interface
implementation
end.
```

More info:

- There is no quoting . No quoting is necessary, or allowed, and our documentation never says to quote these filenames with any character.

- So these 4 lines don't work, as we don't try to interpret the quotes/apostrophes/etc. (and we don't need to, see below):

    ```
    ///  @image("..\docs\File Name.png")
    ///  @image('..\docs\File Name.png')
    ///  @image(´..\docs\File Name.png´)
    ///  @image(`..\docs\File Name.png`)
    ```

- As the documentation says, multiple filenames in `@image` tag are separated by newlines ( https://github.com/pasdoc/pasdoc/wiki/ImageTag ). Ordinary spaces within a filename just work, no need for any quoting.

- The issue is also not related to HTML. As you say, in the output the images are copied to simple names (`image_xx.xxx`) without spaces. And if they would have spaces, we would of course URL-encode them, in case of HTML :)

**Comment by michaliskambi** [comment]
> In addition: docs say multiple paths are separated with newlines but examples show spaces.

Fixed :)

**Comment by vejazi** [comment]
@michaliskambi : Sorry to disagree, but it doesn't work for me.

There is a difference in what we do though: I use relative paths which you don't.
While relative paths do work when having no spaces in the file name it seems file names with spaces fail.

works OK:
    ///  @image(Flow Chart.png)
    ///  @image(..\docs\Flow_Chart.png)
Fails:
    ///  @image(..\docs\Flow Chart.png)

It seems relative paths origin from the path of the source code file containing the image tag.  Is that correct? It would be nice to know when you place images somewhere else in the projects structure.

**Comment by michaliskambi** [comment]
Yes, relative paths are relative to the source code file where they appear.

This works OK for me:

```pascal
{ Sample image with spaces: @image(../docs/something something with spaces.png) }
unit a;
interface
implementation
end.
```

**Comment by vejazi** [comment]
Solved, thank you!

It seems my issue was related to the path separator. You have to use the unix style separator ("/"). A Windows style separator ("\") does not produce an error while processing but no "image_x.png" file is created.

**Comment by vejazi** [comment]
I added a short note about this to the @image tag wiki entry since this costed me some time others could save. Could you please check if it is ok?

**Comment by michaliskambi** [comment]
Oh but that is a bug then :) 

We should accept a relative filename there, just like any other application. So backslash (`\`, Windows-style path separator) should work. Although it should work only on Windows, so I would recommend using slash (`/`/, Unix-style path separator) everywhere, as they will work on both Unix and Windows.

**Comment by michaliskambi** [comment]
Hm, backslashes work for me OK (on Windows). This works OK:

```pascal
{ Sample image with spaces: @image(..\docs\something something with spaces.png) }
unit a;
interface
implementation
end.
```

It correctly reads the `..\docs\something something with spaces.png` file, and creates `image_0.png` in the output (tested with a clean output directory).

( They should not work on Unix, just as they would not work in other Unix applications, since backslash is not a path separator on Unix. )

If they don't work for you, please submit a complete testcase how do you use them. It can be a zip with source code + images.  Make also sure you try the latest PasDoc from snapshots ( https://michalis.ii.uni.wroc.pl/pasdoc-snapshots/ ). Although I don't recall any changes to `@image` since last release.

**Comment by vejazi** [comment]
I'm not sure any more what really happened but I had problems that images were not included properly or not even copied.

I have the impression that somehow when there was a problem in a prior run of pasdoc correcting, like a not existing file, the image tag did not get processed properly on the next run after correcting the issue. 

How are repeated runs handled? I mean you are not copying the file on every run, are you? Otherwise the image_x files would pile up. And it doesn't look like you delete them before each run.

Sorry for the mess I produced here.

**Comment by michaliskambi** [comment]
> How are repeated runs handled? I mean you are not copying the image file on every run, are you? Otherwise the image_x files would pile up. And it doesn't look like you delete them before each run.

We are copying the images on every run. Starting indexing from zero again.

So next runs overwrite images from previous run, if the output directory is the same. (This is true for images as well as all other output files, like HTML.)

For my test with `{ Sample image with spaces: @image(..\docs\something something with spaces.png) }` I manually cleaned the output directory first, to make sure that `image_0.png` produced was really from this PasDoc run. So it seems to work for me OK, i.e. backslashes work on Windows.

> Sorry for the mess I produced here.

No worries :) If you'll have a way to reproduce the problem, please feel free to reopen and submit a report (with files in a zip).
