### ISSUE TITLE
UTF-8 for german not working

### ISSUE THREAD

**Issue by Spruudel** [pasdoc/pasdoc#11]
The generated HTML page displays UTF-8 characters (eg. ü, ä, ö) normally on my local machine, yet when uploaded to GitHub Pages it causes errors.

The head of the html file only contains: 
`<meta http-equiv="content-type" content="text/html; charset=iso-8859-15">`

**Comment by michaliskambi** [comment]
I understand that the characters ü, ä, ö are contained in your own comments?

Currently, the way it works, your source code encoding must be "iso-8859-15". Not UTF-8. Only then will the encoding of the resulting HTML be OK. Can you check is the issue fixed if your source code is using iso-8859-15 encoding for German characters?

Of course, this current state of affairs is a historical artifact. It's 2017 and everything supports UTF-8 now. I can add `de.utf8` language, that works like `de` but in UTF-8, as a first step. And in the future, all languages should just expect UTF-8.

But let's first confirm that the problem is indeed about the encoding :)

**Comment by Spruudel** [comment]
It affects both commented text and text generated by PasDoc (as you can see [here](https://lenni266.github.io/AdvoCat/U_FRUpdater.TFRUpdater.html).

**Comment by michaliskambi** [comment]
Hm, this is a problem on GitHub pages server: the HTTP server answer contains `text/html; charset=utf-8`, which overrides the charset specified in HTML (iso-8859-15). 

![gh_http](https://user-images.githubusercontent.com/1076978/37118076-4b35bfd8-2253-11e8-9b4b-499f1a3c8d12.png)

That's why it works locally. It also works OK on other servers, e.g. this works:
http://michalis.ii.uni.wroc.pl/~michalis/pasdoc-de-test/CastleDialogStates.TStateDialogInput.html
While this has incorrect chars (the *same* HTML, just different server):
http://castle-engine.github.io/castle-game/pasdoc-de-test/CastleDialogStates.TStateDialogInput.html

The only solution in this case is to use UTF-8 encoding for everything on the server. I'll add `de.utf8` language.

**Comment by michaliskambi** [comment]
Implemented.

Please use the latest PasDoc (either compile yourself the version from GitHub https://github.com/pasdoc/pasdoc/ , or use development snapshots: https://github.com/pasdoc/pasdoc/wiki/DevelopmentSnapshots -- they should have the latest version ~15 minutes). Pass the command-line option `--language=de.utf8` and everything should work, tested on http://castle-engine.github.io/castle-game/pasdoc-de-test/CastleDialogStates.TStateDialogYesNo.html .

Note that your source code should also be encoded in UTF-8 now.

I also updated the https://github.com/pasdoc/pasdoc/wiki/OutputLanguage .
