### ISSUE TITLE
The encoding of commentary content is distorted

### ISSUE THREAD

**Issue by opensimply** [pasdoc/pasdoc#118]
The commentary content encoded other than ACSII in range [0x02 , 0x7f]  is distorted as shown below

Original commentary content:    ├──[bin]                Installation tools.

HTML content:                            â”œâ”€â”€[bin]                Installation tools.

**Comment by photograveur** [comment]
The generated HTML pages contain in the header
```html
<meta http-equiv="content-type" content="text/html; charset=utf-8">
```

If you do not save your source code as an UTF-8 encoded file, this will cause a discrepancy with described symptoms. [PasDoc merely copies the input _without_ conversion](https://pasdoc.github.io/OutputLanguage.html#_-notes-about-encoding).

To alter the meta data, you can specify a different encoding as part of your `‑‑language XY.encoding`. Confer [`syntax` values of `LANGUAGE_ARRAY` in `PasDoc_Language.pas`](https://github.com/pasdoc/pasdoc/blob/v0.16.0/source/component/PasDoc_Languages.pas#L446) for valid values.

**Comment by michaliskambi** [comment]
Indeed, the default English language assumes UTF-8 encoding. All characters have to be expressed using UTF-8 encoding.

The only way to change the HTML charset is to use `--language` to indicate a different language and a different encoding, as @photograveur says. I'm guessing this may be a problematic solution -- if you don't want to change your language, only encoding.

Other solutions;

- Express this character using UTF-8 encoding
 
- If you don't want to mess with encodings (because e.g. text editor you use may not handle UTF-8 nicely), and you only care about the HTML output, you can use `@html` tag with HTML entity. This way you specify the HTML entity explicitly like `@html(&rarr;)` or `@html(&#8594)`. ( This character is just an example -- probably you can find your character on https://unicode-table.com/ .)

**Comment by opensimply** [comment]
Thank you. I keep in mind that sources should be UTF-8 encoded.

The current issue occurs  from the fact that sources must obligatory be BOM (Byte Order Mark) encoded. The previous versions have accepted the UTF-8 sources encoded without BOM.

**Comment by Fr0sT-Brutal** [comment]
> The current issue occurs from the fact that sources must obligatory be BOM (Byte Order Mark) encoded. The previous versions have accepted the UTF-8 sources encoded without BOM.

What makes you think so? I'm using BOM-less UTF8 without any issue

**Comment by opensimply** [comment]
I still have it. 
Run the attached test. On Windows I have the difference.  
[test_BOM.zip](https://github.com/pasdoc/pasdoc/files/6049292/test_BOM.zip)

**Comment by michaliskambi** [comment]
As for BOM required:

1. Tested on Linux, there is no difference. Tested @opensimply your testcase with

    ```
    pasdoc testBOM.pas --format=html --title=testBOM --name=testBOM --additional=without_BOM.txt --additional=with_BOM.txt
    ```

    My initial theory: This probably works because on Linux, stuff is UTF-8 by default, FPC considers UTF-8 "standard system encoding" on Linux.

    The change between PasDoc behavior may be due to new FPC version being used to compile it (3.2.0 for PasDoc 0.16.0), and change in Unicode support in FPC. Maybe something now assumes "text file is encoded using standard system encoding (which is <> UTF-8 on Windows)" instead of copying the text literally (not doing any conversions) at some point.

2. Tested on Windows (I have Polish locale) and both files (with and without encoding) are also interpreted the same. See screenshots.

    This doesn't disprove my theory from AD 1 (that, due to new FPC version and Windows encoding <> UTF-8, some difference may occur), it just means I cannot reproduce the problem.

@opensimply what Windows version (and locale) you have? How does the output look for you?

![Screenshot_2021-03-02 testBOM With BOM](https://user-images.githubusercontent.com/1076978/109643459-8abc5600-7b54-11eb-84c5-a1bc547e6d1d.png)
![Screenshot_2021-03-02 testBOM Without BOM](https://user-images.githubusercontent.com/1076978/109643461-8bed8300-7b54-11eb-93d8-9c1b886ebbf6.png)

**Comment by opensimply** [comment]
I think i have localized at least the area the issue goes from.

The issue occurs when using a binary compiled with Delphi ( Delphi 10.3 Version 26.0.34749.6593). A binary compiled with Lazarus makes no issue (Lazarus 2.0.12 i368-win32-win32/win64). In both cases the 32-bit release built mode was used.

The OS is Windows 7 x64. The system locale is English (US), menu language is English (US) too. 

Here are the screenshots of the doc built with Delphi. 
![Delphi_without_BOM](https://user-images.githubusercontent.com/26973313/109691833-24e9c180-7b88-11eb-9caf-88d385fb2493.PNG)
![Delphi_with_BOM](https://user-images.githubusercontent.com/26973313/109691856-2a470c00-7b88-11eb-9290-01899c79c78f.PNG)

What is curios, that Lazarus binary makes an extra vertical indent after the title for BOM-file.
![Lazarus_with_BOM](https://user-images.githubusercontent.com/26973313/109692654-10f28f80-7b89-11eb-8cae-6222e75e9b02.PNG)
![Lazarus_without_BOM](https://user-images.githubusercontent.com/26973313/109692659-12bc5300-7b89-11eb-9ec4-8736d3fd47ec.PNG)

**Comment by michaliskambi** [comment]
1\. Delphi-compiled binaries indeed have different behavior. This is documented, albeit in a very hard to find place :) See the bottom of https://pasdoc.github.io/OutputLanguage , the last 2 paragraphs:

> Note that the encodings listed above apply to the PasDoc version compiled without STRING_UNICODE. This means that PasDoc was compiled with FPC or with non-Unicode Delphi. In particular, the officially released PasDoc versions are compiled with FPC, so the encodings listed above are correct.
> 
> If you compile PasDoc yourself, with newer (Unicode) Delphi, then an alternative version will be used, where all languages are encoded in UTF-8.

Possibly this could be fixed, and Delphi behavior in regards to Unicode treatment brought "in line" with FPC behavior. Admittedly it was never a priority -- as we distribute PasDoc releases compiled with FPC. But PRs to do it would be welcome.

2\. The weird additional space in case of "with BOM" output with FPC was due to a bug, we didn't skip the BOM in case of introduction, conclusion and various other text files (our logic to skip BOM was only used for Pascal sources). So the BOM landed in the middle of the HTML file, and both Firefox and Google Chrome decided it is a weird character that separates the header from the 1st paragraph, changing the margins interpretation, and in effect adding extra space between header and 1st paragraph.

Thanks for noticing this -- fixed!

**Comment by opensimply** [comment]
Thank you for the detailed explanation!
