### ISSUE TITLE
Error using GraphViz 'dot' program with GVUses.dot / GVClasses.dot

### ISSUE THREAD

**Issue by BertLaegel** [pasdoc/pasdoc#124]
dot -T png GVUses.dot > GVUses.png
Error: GVUses.dot: syntax error in line 1 near 'DiGraph'
(PasDoc 0.16.0 [2021-02-07|FPC 3.2.0|MSWindows|64], GraphViz 2.47.2)

**Comment by michaliskambi** [comment]
How does your `GVUses.dot` look like?

And/or, how do you generate it, what is you `pasdoc` command-line and input?

Testing here with GraphViz 2.40.1 on Debian, doing `dot -T png GVUses.dot  > a.png` works OK. I see you're on Windows and use GraphViz 2.47.2 -- but it would be weird if OS/minor version creates a problem here. The error message suggests that there's something basic wrong in `GVUses.dot`. It should look like this:

```
DiGraph Uses {
  "ok_abstract_sealed" [href="ok_abstract_sealed.html"]
}
```

**Comment by BertLaegel** [comment]
Hope I did not sent it twice, first email with the ‘*.dot’ files did not seem to get through…

 

Hi there,

I used the GUI version of PasDoc, checking the check boxes in the ‘graphs’ tab to get the ‘GVClasses.dot’ and ‘GVUses.dot’ which I have attached. I use the GraphViz ‘dot’ program from the command line as described on the wiki page (GraphVizSupport · pasdoc/pasdoc Wiki (github.com) <https://github.com/pasdoc/pasdoc/wiki/GraphVizSupport> ). 
There is not much to find on the internet about such a problem except one thing that it might be related to ‘line endings or BOM markers’, however, I did not modify the 2 files in any way…
I much appreciate your input!
Best Regards,
Bert

 

 

Von: Michalis Kamburelis ***@***.***> 
Gesendet: Donnerstag, 17. Juni 2021 17:13
An: pasdoc/pasdoc ***@***.***>
Cc: BertLaegel ***@***.***>; Author ***@***.***>
Betreff: Re: [pasdoc/pasdoc] Error using GraphViz 'dot' program with GVUses.dot / GVClasses.dot (#124)

 

How does your GVUses.dot look like?

And/or, how do you generate it, what is you pasdoc command-line and input?

Testing here with GraphViz 2.40.1 on Debian, doing dot -T png GVUses.dot > a.png works OK. I see you're on Windows and use GraphViz 2.47.2 -- but it would be weird if OS/minor version creates a problem here. The error message suggests that there's something basic wrong in GVUses.dot. It should look like this:

DiGraph Uses {
  "ok_abstract_sealed" [href="ok_abstract_sealed.html"]
}

**Comment by michaliskambi** [comment]
@BertLaegel I'm afraid the attachments did not reach me. Please simply open the bugreport https://github.com/pasdoc/pasdoc/issues/124 in the web browser, and make a comment this way, attaching files (you can pack in zip any other files).

**Comment by BertLaegel** [comment]
That should work and thanks again looking into that issue.
[GVClasses.zip](https://github.com/pasdoc/pasdoc/files/6678698/GVClasses.zip)

**Comment by michaliskambi** [comment]
Sorry for taking so long to address this!

Fixed. The fix is in the source code -- to get the fixed version now, you can either compile PasDoc yourself from the source code, or take a compiled snapshot from https://pasdoc.github.io/DevelopmentSnapshots .

Background:

I initially tested on:

- Linux (fresh Debian testing) with GraphViz 2.40.1
- Windows with GraphViz 2.40.1-5 (GraphViz  from latest Cygwin)

In both cases, doing on the command-line:

```
dot GVClasses.dot -T png > GVClasses.png
dot GVUses.dot -T png > GVUses.png
```

worked OK, i.e. created proper PNG files without any errors. 

But then I tested:

- Windows with GraphViz 2.48.0 (from zip version on https://graphviz.org/download/ )

... and it failed just as you described. Testing, it seems that GraphViz just started (in some version between 2.40.1 and 2.47.2, it seems) to enforce that initial `digraph` keyword is all lowercase, while PasDoc was writing `DiGraph`. After a trivial fix (we now generate .dot files with lowercase `digraph`) it works OK.

Attaching output for your testcase.
![GVClasses](https://user-images.githubusercontent.com/1076978/126917708-e9efa9f0-9733-4749-a4f7-4ce4125452fb.png)
![GVUses](https://user-images.githubusercontent.com/1076978/126917710-f840dedc-38bb-4e5e-a31e-7fa0b44043b6.png)

**Comment by BertLaegel** [comment]
Dear Michalis,

 

This works. Thanks a lot for your efforts!

 

Best regards,

 

Bert

 

Von: Michalis Kamburelis ***@***.***> 
Gesendet: Montag, 26. Juli 2021 02:02
An: pasdoc/pasdoc ***@***.***>
Cc: BertLaegel ***@***.***>; Mention ***@***.***>
Betreff: Re: [pasdoc/pasdoc] Error using GraphViz 'dot' program with GVUses.dot / GVClasses.dot (#124)

 

Sorry for taking so long to address this!

Fixed. The fix is in the source code -- to get the fixed version now, you can either compile PasDoc yourself from the source code, or take a compiled snapshot from https://pasdoc.github.io/DevelopmentSnapshots .

Background:

I initially tested on:

*	Linux (fresh Debian testing) with GraphViz 2.40.1
*	Windows with GraphViz 2.40.1-5 (GraphViz from latest Cygwin)

In both cases, doing on the command-line:

dot GVClasses.dot -T png > GVClasses.png
dot GVUses.dot -T png > GVUses.png

worked OK, i.e. created proper PNG files without any errors.

But then I tested:

*	Windows with GraphViz 2.48.0 (from zip version on https://graphviz.org/download/ )

... and it failed just as you described. Testing, it seems that GraphViz just started (in some version between 2.40.1 and 2.47.2, it seems) to enforce that initial digraph keyword is all lowercase, while PasDoc was writing DiGraph. After a trivial fix (we now generate .dot files with lowercase digraph) it works OK.

Attaching output for your testcase.
 <https://user-images.githubusercontent.com/1076978/126917708-e9efa9f0-9733-4749-a4f7-4ce4125452fb.png> 
 <https://user-images.githubusercontent.com/1076978/126917710-f840dedc-38bb-4e5e-a31e-7fa0b44043b6.png>
