### ISSUE TITLE
HTML Outbut errors

### ISSUE THREAD

**Issue by jdelauney** [pasdoc/pasdoc#14]
Hi, 
first sorry for*Outbut --> OutPut.
Like i said in issue #12 . I've finally got a respectable result but i've notice some errors :
![2018-03-09_152615](https://user-images.githubusercontent.com/29355534/37231850-fb7ebc9c-23ec-11e8-819c-845b74f6e9c7.jpg)
![2018-03-09_153012](https://user-images.githubusercontent.com/29355534/37231875-0e689da0-23ed-11e8-9e05-4f4dbe4d302a.jpg)
here like you see the %region% will not be appear

-----------------------

![2018-03-09_152348](https://user-images.githubusercontent.com/29355534/37231901-33f4ee02-23ed-11e8-8f97-5814851cf2c6.jpg)
here links (lenght) here are not display in the same way

--------------------

![2018-03-09_152437](https://user-images.githubusercontent.com/29355534/37231952-53a9b566-23ed-11e8-8f15-079c83306fe3.jpg)

![2018-03-09_225956](https://user-images.githubusercontent.com/29355534/37232058-b05e4c4a-23ed-11e8-9aa4-5d2c2d7e096d.jpg)

here same as above and param have return line instead it will be on the same line (more pleasant)

-------------------

![2018-03-09_230255](https://user-images.githubusercontent.com/29355534/37232178-331823ae-23ee-11e8-9e06-7d17d2ea43d5.jpg)
![2018-03-09_152839](https://user-images.githubusercontent.com/29355534/37232211-5da1049c-23ee-11e8-84b2-909a97b0c503.jpg)

Here in "All functions and procedure" order are not repsected and see the Sqrt function

----------------

I have a question it is possible to avoid @abstract and @br tag. ?

Thanks in advance. 

Best regards

**Comment by michaliskambi** [comment]
> here like you see the %region% will not be appear

I added removing %region, %endregion etc. from the beginning of comment.

> here links (lenght) here are not display in the same way

Because the 1st case is not a link. It's the name of the current item.

Note that if you're using --auto-link, it recognizes these two cases:

```
{ This is Foo. }
procedure Foo;
```

is equivalent to

```
{ This is @name. }
procedure Foo;
```

While

```
{ Look at Bar. }
procedure Foo;
```

is equivalent to

```
{ Look at @link(Bar). }
procedure Foo;
```

This is documented at https://github.com/pasdoc/pasdoc/wiki/AutoLinkOption .

> here same as above and param have return line instead it will be on the same line (more pleasant)

The fact that 1st Clamp has `Clamp` as link, 2nd one not, is a conquence of auto-linking and overloading. The 1st `Clamp` links to the 2nd one, PasDoc cannot know that this is probably not what you want.

In general, if you use `--auto-link`, then you should probably also use `--auto-link-exclude` to *not* auto-link some stuff. Looking at your screenshot, you probably do not want these words to be auto-linked:

```
clamp
min
max
```

Or you can use other options listed on https://github.com/pasdoc/pasdoc/wiki/AutoLinkOption to mitigate this.

> Here in "All functions and procedure" order are not repsected and see the Sqrt function

As for order: PasDoc sorts the order of many things. You can control it using the `--sort` option https://github.com/pasdoc/pasdoc/wiki/SortOption (or the appropriate option in pasdoc_gui). However the listings that gather all the units (like _All Functions and Procedures_) are always sorted, as presenting them unsorted was considered not very useful for users (the order would then be defined by the order of units on the PasDoc command-line, which is usually not very useful for the reader of the documentation).

As for the `Sqrt` comment: PasDoc sees the comments above your `Sqrt`, and considers them to be a documentation for `Sqrt`. Moreover, it glues multiple single-line (`//`) comments. PasDoc has no reliable way to guess that `//function Length...` is probably not something you wanted to show to user.

PasDoc is by default "eager" to treat your comments as documentation, see https://github.com/pasdoc/pasdoc/wiki/WhereToPlaceComments . This means that you have to consider what comments you have before each identifier.

It's best to just put some comment at `Sqrt`:

```
// ...
//--- Trigonometric functions

{ Calculate square root. }
function Sqrt(...)
```

If you don't want to show any documentation, then just place an empty documentation comment: 

```
// ...
//--- Trigonometric functions

{ }
function Sqrt(...)
```

An alternative solution is not stop PasDoc from being so "eager" to consider comments as documentation. Instead, use the option `--marker` or `--staronly` to make PasDoc only cosider some comments (marked with a special char) as documentation: https://github.com/pasdoc/pasdoc/wiki/CommentMarker 

How to avoid writing `@abstract`: Use `--auto-abstract`: https://github.com/pasdoc/pasdoc/wiki/AutoAbstractOption 

How to avoid writing `@br`:
- There is no shorter way of making an explicit newline (`<br>` in HTML output). 
- But on the other hand, you should not need to use this much often, both in HTML and LaTeX you should seldom need to force a line break. Instead, allow the browser to break your line based on window width, and use paragraphs to split text into chunks. To make a new paragraph, simply make an empty line, see: https://github.com/pasdoc/pasdoc/wiki/WritingDocumentation .

**Comment by michaliskambi** [comment]
I forgot to answer this:

> param have return line instead it will be on the same line (more pleasant)

In many cases, this return line is pleasant, so we want to keep it by default :) In general, it seems you are repeating the declaration (`: Integer`) in the documentation, while we generally don't do that in the documentation. The type of the parameter is visible already in the declaration that PasDoc is showing.

That said, you can change the display of this using CSS. A number of solutions can be found using Google, e.g. https://stackoverflow.com/questions/1713048/how-to-style-dt-and-dd-so-they-are-on-the-same-line . Playing a bit, this CSS accomplishes what you need:

```
<style>
dl.parameters dd {
  display: inline;
  margin: 0;
}
dl.parameters dd:after{
  display: block;
  content: '';
}
dl.parameters dt{
  display: inline-block;
  /* min-width: 100px; */
}
</style>
```

Place the above snippet in a file like `my_style.html` and call pasdoc like `pasdoc my_unit.pas --html-head my_style.html` to use this.

**Comment by michaliskambi** [comment]
P.S. In case you use `pasdoc_gui`, I just noticed that it does not expose an option equivalent to command-line `--html-head`, thus my previous comment was not possible with pasdoc_gui. Fixed now, pasdoc_gui has now option `Additional HTML <head> content`.

To test, you can compile PasDoc yourself (get from GitHub sources: https://github.com/pasdoc/pasdoc/ ), or use snapshots: https://github.com/pasdoc/pasdoc/wiki/DevelopmentSnapshots .
