### ISSUE TITLE
It seems the @raises tag is not working

### ISSUE THREAD

**Issue by silvioprog** [pasdoc/pasdoc#15]
Hello.

Please consider the following small doc:

```delphi
    { Specifies the library to be loaded dynamically.

      @raises(EBrookOpNotAllowedLoadedLib if the library is already loaded.)}
    property LibraryName: TFileName read FLibraryName write SetLibraryName;
```
However, it seems the `@raises` tag is not parsed :disappointed: :

![image](https://user-images.githubusercontent.com/1456829/37628452-48bbecdc-2bb8-11e8-9f6c-cfe84fdc2424.png)

I'm using PasDoc GUI + PasDoc 0.15.0 and [this configuration](https://github.com/silvioprog/brookframework/blob/tardigrade/PasDoc.pds).

**Comment by silvioprog** [comment]
It is by design. It works for methods, not for property setters.

**Comment by michaliskambi** [comment]
I think we should enable it also for properties. As your example shows, it is useful there. The getter/setter methods are often private, so there is no other place to document exceptions they raise than at the property.

I'll do it later today:)

(The documentation author should probably mention at docs whether the exception can be raised by getter or setter, like `@raises ESomething if setting an incorrect value`. But that's just a suggestion.)

**Comment by michaliskambi** [comment]
Fixed. `@raises` is now allowed on properties.

BTW, also `@param` is allowed on properties (since it makes sense for array properties).

Actually, `@raises` and `@param` are now allowed on *any* Pascal identifier (like a class, or a unit, or a simple variable..), since that was easiest to implement. But the usage probably should be limited to methods and properties:)

This testcase now works OK: https://github.com/pasdoc/pasdoc/blob/master/tests/testcases/ok_param_raises_at_property.pas .

**Comment by silvioprog** [comment]
Thanks for implementing. It worked in my code too! :smiley:
