### ISSUE TITLE
TCollectionNotification = (...);

### ISSUE THREAD

**Issue by andre2007** [pasdoc/pasdoc#173]
File `Embarcadero\\Studio\\19.0\\source\\rtl\\common\\System.Classes.pas` contains this type declaration:

``` delphi
TCollectionNotification = (cnAdded, cnExtracting, cnDeleting);
```

Pasdoc will create this information in SimpleXML:
``` xml
<type name="TCollectionNotification = (...);">
  </type>
```

I would expect to see the names instead of ...
Same issue for other types too (TListNotification, TListAssignOp, ...)

**Comment by michaliskambi** [comment]
Actually the type `name` should be just `TCollectionNotification`. 

The `declaration`, in case of enum type, should contain `xxx = (...)`. This declaration is deliberately shortened ("..." instead of actual enum names) because the enum names should be placed as subitems.

I tested on latest Delphi I have, but there `TCollectionNotification` is no longer an enum, i.e. it refers to enum in another unit:

```xml
  <type name="TCollectionNotification" declaration="TCollectionNotification = System.Generics.Collections.TCollectionNotification;">
  </type>
```

But e.g. `TListNotification` is a simple enum, and it looks OK:

```
  <type name="TListNotification" declaration="TListNotification = (...);">
  </type>
```

This is in XML after running:

```
pasdoc 'c:/Program Files (x86)/Embarcadero/Studio/22.0/source/rtl/common/System.Classes.pas' --format=simplexml
```

The error here is IMHO that we don't list `lnAdded` and other subitems in enum... So I just fixed it :) You will now get

```xml
  <type name="TListNotification" declaration="TListNotification = (...);">
    <constant name="lnAdded" declaration="lnAdded">
    </constant>
    <constant name="lnExtracted" declaration="lnExtracted">
    </constant>
    <constant name="lnDeleted" declaration="lnDeleted">
    </constant>
  </type>
```

Each enum constant may have an additional description, if provided in source code. This is visible in this test:

```xml
  <type name="TMyEnum" declaration="TMyEnum = (...);">
    <description><detailed> </detailed></description>
    <constant name="meOne" declaration="meOne">
      <description><detailed>Description of meOne follows.</detailed></description>
    </constant>
    <constant name="meTwo" declaration="meTwo">
    </constant>
    <constant name="meThree" declaration="meThree">
      <description><detailed>Description of meThree, with some link: TMyClass.MyField.</detailed></description>
    </constant>
  </type>
```
