### ISSUE TITLE
SimpleXML: Missing information for properties regarding read / write

### ISSUE THREAD

**Issue by andre2007** [pasdoc/pasdoc#174]
The Delphi component `TCustomEdit` has these properties

``` delphi
    property SelLength: Integer read GetSelLength write SetSelLength;
    property SelText: string read GetSelText;
    property KeyboardType: TVirtualKeyboardType read GetKeyboardType write SetKeyboardType default TVirtualKeyboardType.Default;
   
```

The Pasdoc SimpleXML output is as following:
``` xml
    <property name="SelLength" indexdecl="" type="Integer" reader="" writer="" default="0" defaultid="" nodefault="0" storedid="">
    </property>
    <property name="SelText" indexdecl="" type="string" reader="" writer="" default="0" defaultid="" nodefault="0" storedid="">
    </property>
  <property name="KeyboardType" indexdecl="" type="" reader="" writer="" default="0" defaultid="" nodefault="0" storedid="">
    </property>
```

From the output it is not visible that property `SelText` is read only. Can you add these information to SimpleXML output?
Also the information if a property has a default value is missing.

**Comment by michaliskambi** [comment]
Looking at code, I noticed that PasDoc information about property (TPasProperty) already had properties `TPasProperty.Reader`, `TPasProperty.Writer`, but they were never filled by the parser. Looks like it was unfinished plan to parse them.

Well I finished it now :) We now parse property 

- read XXX
- write XXX
- default XXX
- nodefault
- stored XXX

The output for your case will be

```xml
    <property name="SelLength" indexdecl="" type="Integer" reader="GetSelLength" writer="SetSelLength" default="False" defaultid="" nodefault="False" storedid="">
    </property>
    <property name="SelText" indexdecl="" type="string" reader="GetSelText" writer="" default="False" defaultid="" nodefault="False" storedid="">
    </property>
    <property name="KeyboardType" indexdecl="" type="TVirtualKeyboardType" reader="GetKeyboardType" writer="SetKeyboardType" default="False" defaultid="TVirtualKeyboardType . Default" nodefault="False" storedid="">
    </property>
```

Also boolean information (nodefault, default) is now output as clear "False" or "True" instead of weird 0 / -1.

Note about the difference between `default` and `defaultid` in XML output:
 
1. `default` (boolean) says if the property is default of this class. Like `property Items[I: Integer]: String read GetItems; default;` should cause it.

2. `defaultid` (string) is the property default value.Like `property Xxx: Integer default 123;` should cause it.

Maybe these should have more obvious names (`default_in_class`, `default_value`) to not be confusing? 

Also note that AD 1 ("default in class") is not yet detected by parser, please submit an issue if you need this too.

**Comment by michaliskambi** [comment]
> Maybe these should have more obvious names (default_in_class, default_value) to not be confusing

I went ahead and did the rename, so now the output will be

```xml
    <property name="SelLength" indexdecl="" type="Integer" reader="GetSelLength" writer="SetSelLength" default_in_class="False" default_value="" nodefault="False"   stored="">
    </property>
    <property name="SelText" indexdecl="" type="string" reader="GetSelText" writer="" default_in_class="False" default_value="" nodefault="False"   stored="">
    </property>
    <property name="KeyboardType" indexdecl="" type="TVirtualKeyboardType" reader="GetKeyboardType" writer="SetKeyboardType" default_in_class="False" default_value="TVirtualKeyboardType . Default" nodefault="False"   stored="">
    </property>
```

**Comment by andre2007** [comment]
Fantastic, thanks a lot for your quick help. The output looks great.
