### ISSUE TITLE
Escaping of characters (<>) in SimpleXML

### ISSUE THREAD

**Issue by andre2007** [pasdoc/pasdoc#175]
File `Embarcadero\Studio\19.0\source\fmx\FMX.Controls.Presentation.pas` contains these coding:

``` delphi
    /// <summary>Initializes proxy by control and model and create link with presentation by using
    /// <c>FMX.Presentation.Messages.TMessageSender.CreateReceiver</c></summary>
    /// <param name="AModel">Model instance of |<b>AControl</b>|</param>
    /// <param name="AControl">Control, which supports using of presentation (usually <b>TPresentedControl</b>)</param>
    constructor Create(const AModel: TDataModel; const AControl: TControl); overload; virtual;
```

Pasdoc will create this SimpleXML output:

``` xml
 <routine name="Create" type="constructor" declaration="constructor Create(const AModel: TDataModel; const AControl: TControl); overload; virtual;">
      <param name="AModel">Model instance of |<bold>AControl</bold>|</param>
      <param name="AControl">Control, which supports using of presentation (usually <bold>TPresentedControl</bold>)</param>
```

My gut feeling ist, the characters `<` and `>` should be escaped in SimpleXML? This seems not to be valid XML?

**Comment by michaliskambi** [comment]
Testing, PasDoc is correct here. The bare `>` characters *are* converted to `&gt;`...

...unless they actually mean something :) And in this case the three slashes are interpreted by PasDoc as HelpInsight comment, see https://pasdoc.github.io/WritingDocumentation . So we actually interpret `<summary>`, `<b>`, `<param>` just like HelpInsight would. So we internally convert

- `<b>something</b>` -> `@bold(something)` (a PasDoc tag https://pasdoc.github.io/BoldAndItalicTags )  -> and then SimpleXML outputs this as `<bold>something</bold>`

- `<param name="xxx">something</param>` -> `@param(xxx something)` (PasDoc tag https://pasdoc.github.io/ParamReturnsRaisesTag ) -> and then SimpleXML writes it as `<param name="xxx">something</param>`

The conjunction of HelpInsight and SimpleXML is funny in case of `param` :) It *seems* like we didn't process `<param...>` and just copied it to XML output. But actually we did, it just looks the same :) We interpreted 

```
<param name="AModel">Model instance of |<b>AControl</b>|</param>
```

as adding a documentation for parameter `AModel` following HelpInsight syntax, just as this would do:

 ```
@param(AModel Model instance of |@bold(AControl)|)
```

And then SimpleXML turned it back into


```
<param name="AModel">Model instance of |<bold>AControl</bold>|</param>
```

just because SimpleXML happened to choose output XML that looks exactly like HelpInsight input. (And that's good IMHO, it makes it consistent.)

You can test that actually something happens by adding e.g. bare `<` character there, like `Test > ` in the input. In the output it will be `Test &gt; `.

Attaching my test of it.

[ok_escape_html.pas.txt](https://github.com/pasdoc/pasdoc/files/10452703/ok_escape_html.pas.txt)

Closing -- as far as I see we actually behave correctly here. We interpret HelpInsight in the comment, and SimpleXML outputs them as XML elements (that sometimes looks exactly the same :) ).

**Comment by andre2007** [comment]
Thanks for checking. Yes, the behavior is correct.
