### ISSUE TITLE
Dot files are rejected by dot

### ISSUE THREAD

**Issue by rsgrimes** [pasdoc/pasdoc#180]
Using PasDoc 0.16.0, I am trying to generate a class diagram with dot 0.7.1. According to the wiki, I should call dot manually with something like the following:

```
$ dot -Grankdir=LR -T png GVClasses.dot > GVClasses.png
Error: GVClasses.dot: syntax error in line 1 near 'DiGraph'
```

This is the content of GVClasses.dot:

```
DiGraph Classes {
  "IAdjFreqParm" -> "IInterface"
  "IAdjFreqParm" [href="TrajGenAdjOneParm.IAdjFreqParm.html"]
  "IAdjParmIntf" -> "IInterface"
  "IAdjParmIntf" [href="TrajectoryInterfaces.IAdjParmIntf.html"]
  "IAdjOneParm" -> "IAdjParmIntf"
  "IAdjOneParm" [href="TrajGenAdjOneParm.IAdjOneParm.html"]
}
```

Very generic! What gives?

Update:

It turns out that dot is case sensitive; replacing 'DiGraph' with 'digraph' makes it work. So PasDoc generates bad .dot files, but the fix is easy!

**Comment by michaliskambi** [comment]
Thanks for the report!

Indeed, I see you found the culprit already. And this was already fixed in 2021, in this commit: https://github.com/pasdoc/pasdoc/commit/62a6f92d85dd0d513b23773379761c2a04fbf12c . You can get the fixed version e.g. from our "snapshots", https://pasdoc.github.io/DevelopmentSnapshots .

We didn't make a new release since February 2021, so more than 2 years now. We really should make a new release ;)

**Comment by rsgrimes** [comment]
Thanks to you for following up and for the great tool! While I prefer Doxygen overall, when working in Delphi, this is a plenty good substitute! I wish I had heard of it sooner - I only recently discovered it. I've been meaning to do something better in my Delphi documentation; PasDoc is just the thing I needed!
