### ISSUE TITLE
Specify multiple markers

### ISSUE THREAD

**Issue by circular17** [pasdoc/pasdoc#192]
In my documentation, I use two different markers `*` and `**` for comment. One star is for the main entity and double star is for a subitem. This is helpful because sometimes, I would like to put things together, for examples some functions apply to some types, even though they are not part of the type.

While I don't expect pasdoc to group them together, I would like to be able to specify that both are markers for comments. So that I keep the information for my custom documentation tool while making it transparent for pasdoc.

The markers could be specified for example using multiple `-marker` parameters, or with a `-markers` parameters that takes multiple markers separated by commas `,`.

**Comment by circular17** [comment]
As a matter of fact, it is possible to define multiple markers in the GUI of PasDoc:
<img width="789" alt="gui_multiple_markers" src="https://github.com/pasdoc/pasdoc/assets/9092455/2af9fa93-8dcc-4310-910b-463e1a6c4814">

**Comment by michaliskambi** [comment]
Testing, multiple markers already work from the command-line :) As found out by @DomingoGP in https://github.com/bgrabitmap/bgrabitmap/issues/228#issuecomment-1854807705 .

Testcase 1: 
- https://github.com/pasdoc/pasdoc/blob/master/tests/testcases/ok_multiple_markers.pas
- Command-line: `pasdoc --marker=foo --marker=bar --marker-optional ...`

Testcase 2: 
- https://github.com/pasdoc/pasdoc/blob/master/tests/testcases/ok_multiple_markers_prefix.pas
- Command-line: `pasdoc '--marker=*' '--marker=**' --marker-optional ...`

I still did a minor improvement: We sort the markers by length now, so that longer markers (of which the shorter marker may be a prefix) are checked earlier. This means that order **should not matter anymore** :) This addresses the note "Attention the order in which we indicate the markers is important." from @DomingoGP , https://github.com/bgrabitmap/bgrabitmap/issues/228#issuecomment-1854807705 .

I also improved docs to document this better, https://pasdoc.github.io/CommentMarker .

The fix is committed to source code on GitHub master branch, soon (in ~15 minutes) the snapshots on https://pasdoc.github.io/DevelopmentSnapshots will also contain it.
