### ISSUE TITLE
pasdoc configuration via command-line

### ISSUE THREAD

**Issue by flashpixx** [pasdoc/pasdoc#31]
I'm using PasDoc within a Docker container, so it would be nice, if I can create the PasDoc `settings.psd` via comandline with a default setting type, so I can modify it with tools like `nano` or `vi` on my Docker commandline (the psd file extension match also to Adobe Photoshop, an ini or yaml file could be better)

**Comment by michaliskambi** [comment]
For this you can use the command-line `pasdoc` instead of the `pasdoc_gui`, and create a simple shell script (e.g. using Unix `bash`) to call `pasdoc` with proper options. *All* the options can be provided on the command-line.

As an example, https://castle-engine.io/apidoc/html/ is generated by Jenkins using Docker for each job :) My shell script that does this is on https://github.com/castle-engine/castle-engine/blob/master/doc/pasdoc/mk_docs.sh . But it's very complicated by this point.

For a simple usage you just create a simple shell script like this:

```
#!/bin/bash
set -eu

PASDOC_FORMAT=html
OUTPUT_PATH=output/
PRETEND_OS=LINUX
pasdoc \
  --format "$PASDOC_FORMAT" \
  --output "$OUTPUT_PATH" \
  --define "$PRETEND_OS" \
  --define FPC --define VER3 --define VER3_0 --define VER3_0_4 --define PASDOC \
  --write-uses-list \
  --title "Castle Game Engine" \
  --source *.pas
...
```

In general I agree that this feature would be useful (and in general, it would be nice if command-line `pasdoc` was able to read `xxx.psd` files). But, since you can write a shell script, this is not high priority now.

And yes, `.psd` is unfortunate :) I would probably prefer a long extension `.pasdoc-settings` now. Or maybe just `.ini`, but that's more generic.

Thank you for all the submissions to PasDoc! I appreciate them, and keep them coming :)

**Comment by flashpixx** [comment]
Thanks a lot for this, I'm using a shell script in my Docker container:

```
#!/bin/sh -e

FILELIST=$(mktemp)
TARGETDIR="docs"
DOCTITLECMD=""
DOCLANG=""

if [ -n "$2" ]; then
    TARGETDIR=$2
fi

if [ -n "$DOCTITLE" ]; then
    DOCTITLECMD="--title $DOCTITLE"
fi 

if [ -n "$DOCLANG" ]; then
    DOCLANGCMD="--language $DOCLANG"
fi 


# create target directory
mkdir -p $TARGETDIR
# recursive parsing alls pas files
find $1 -type f -iname "*.pas" > $FILELIST
# copy external template additionals like Boostrap css
cp -f /opt/template/external/*.* $TARGETDIR || true
# running pasdoc and ignore parsing errors
pasdoc -v 3 $DOCTITLECMD -E $TARGETDIR --cache-dir $(mktemp -d) --graphviz-uses --graphviz-classes --link-gv-uses svg --link-gv-uses svg  --use-tipue-search --css /opt/template/layout.css --footer /opt/template/footer.htm --html-head /opt/template/header.htm --html-body-begin /opt/template/body-begin.htm --html-body-end /opt/template/body-end.htm -S $FILELIST || true
```

but I have added the `--name` parameter to the command and it does not generate any output within the HTML output, with `--title` an output is generated

**Comment by michaliskambi** [comment]
The `--name` option only specifies the base file name for some formats (LaTeX, HtmlHelp). It is unused by the (default) HTML output format. See https://github.com/pasdoc/pasdoc/wiki/NameOption .

Indeed, `--title` is what you want, this sets HTML title.

**Comment by michaliskambi** [comment]
I see in your script you use

```
--cache-dir $(mktemp -d)
```

But this way you have a different cache directory for each PasDoc run, as `mktemp -d` will return new directory each time. In effect, cache is not useful. That is, it will work, but actually you don't achieve any gain from using cache this way, since every execution of PasDoc will start with an empty cache.

Cache is only useful if you use *the same* --cache-dir value for multiple executions of PasDoc. See https://github.com/pasdoc/pasdoc/wiki/CacheOption . So you should rather do something like

```
mkdir -p /tmp/pasdoc-cache/
pasdoc --cache-dir /tmp/pasdoc-cache/ ...
```

**Comment by flashpixx** [comment]
A static directory does not work also, because pasdoc runs within a Docker container, which will be instantiate on each change on the source codes again, so the cache directory is not stored outside the container. I would like to use pasdoc in a _continouse integration_ system like CircleCI / GitlabCI

**Comment by michaliskambi** [comment]
I believe this is addressed now by https://github.com/pasdoc/pasdoc/wiki/ConfigFileOption , which is a simple way to put command-line options in an external file.

Note that format of https://github.com/pasdoc/pasdoc/wiki/ConfigFileOption and `pasdoc_gui` .psd files is different. (I would like one day to support .psd within command-line pasdoc too, but I think it's not necessary for this case.)
