### ISSUE TITLE
Test suite issues

### ISSUE THREAD

**Issue by Fr0sT-Brutal** [pasdoc/pasdoc#46]
So I ran tests over `master` branch and got some differences
```
Path	Filename	Extension	Status	Lines added	Lines removed	Last Modified	Size
tests/testcases_output/html/large_test/AllFunctions.html	AllFunctions.html	.html	Modified	12	12		
tests/testcases_output/html/large_test/AllIdentifiers.html	AllIdentifiers.html	.html	Modified	27	27		
tests/testcases_output/html/ok_nested_types/ok_nested_types.html	ok_nested_types.html	.html	Modified	55	55		
tests/testcases_output/html/warning_back_comment/PASDOC-OUTPUT	PASDOC-OUTPUT		Modified	5	5		
tests/testcases_output/html/warning_back_comment_class/PASDOC-OUTPUT	PASDOC-OUTPUT		Modified	1	1		
tests/testcases_output/htmlhelp/large_test/AllFunctions.html	AllFunctions.html	.html	Modified	12	12		
tests/testcases_output/htmlhelp/large_test/AllIdentifiers.html	AllIdentifiers.html	.html	Modified	27	27		
tests/testcases_output/htmlhelp/large_test/docs.hhk	docs.hhk	.hhk	Modified	31	31		
tests/testcases_output/htmlhelp/ok_nested_types/ok_nested_types.html	ok_nested_types.html	.html	Modified	53	53		
tests/testcases_output/htmlhelp/warning_back_comment/PASDOC-OUTPUT	PASDOC-OUTPUT		Modified	5	5		
tests/testcases_output/htmlhelp/warning_back_comment_class/PASDOC-OUTPUT	PASDOC-OUTPUT		Modified	1	1		
tests/testcases_output/latex/warning_back_comment/PASDOC-OUTPUT	PASDOC-OUTPUT		Modified	5	5		
tests/testcases_output/latex/warning_back_comment_class/PASDOC-OUTPUT	PASDOC-OUTPUT		Modified	1	1		
tests/testcases_output/latex2rtf/warning_back_comment/PASDOC-OUTPUT	PASDOC-OUTPUT		Modified	5	5		
tests/testcases_output/latex2rtf/warning_back_comment_class/PASDOC-OUTPUT	PASDOC-OUTPUT		Modified	1	1		
```
Are expected results non-actual or I have tests run incorrectly?

**Comment by michaliskambi** [comment]
This is fixed in 75% now. I found 4 problems when testing it, and 3 are fixed now :)

It all worked OK without reporting any differences (also before applying your PRs) for me with FPC 3.0.4 on Linux.

But testing, indeed the output was not "stable" when I checked it on other OSes (Windows, while I usually tested with Linux) or even FPC versions (FPC 3.3.1 was sorting "AllIdentifiers" differently than FPC 3.0.4 before my improvements, as in some cases items were considered equal and thus any order was allowed). Fixed now:

1. Different order of "AllXxx" lists is fixed.

2. Different order of `test_links_to_dot_names/*.pas` result is fixed.

3. Newline differences between Unix and Windows (required GIT config in `.gitattributes`) should not bite us anymore.

4. Not yet fixed: Line numbers are sometimes incorrect (on Linux, testcases with "back comment" exhibit error-by-1 when reporting line numbers of some warnings; weirdly, *some* line numbers are correct (and equal to Windows result), only some are wrong).

Note that you will probably need to make a "fresh GIT clone" in order for the AD 3 to be fixed. Only then the `.gitattributes` inside the repository will correctly work and make all the files follow Windows line endings (when on Windows).

Thank you for reporting this! This uncovered a few issues worth fixing :)

**Comment by Fr0sT-Brutal** [comment]
Wow, so many issues revealed :rofl:

**Comment by Fr0sT-Brutal** [comment]
Renamed the issue `cause seems I use it right.

Noticed that following tests seem to not being run:
error_back_comments.pas
ok_longcode_indentation.pas
ok_utf8_failchar.pas

**Comment by michaliskambi** [comment]
> Noticed that following tests seem to not being run:

Thanks, fixed. (And I renamed error_back_comments.pas -> warning_back_comments.pas )

**Comment by michaliskambi** [comment]
The last issue is now fixed.

(Number 4 in my comment last weekend, """
Line numbers are sometimes incorrect (on Linux, testcases with "back comment" exhibit error-by-1 when reporting line numbers of some warnings; weirdly, some line numbers are correct (and equal to Windows result), only some are wrong).
""""
)

Tests now pass perfectly on Windows and Linux, and should pass regardless of FPC version used. I.e. the output is exactly equal in every case.
