### ISSUE TITLE
[bug] Parser does not support nested comments

### ISSUE THREAD

**Issue by Fr0sT-Brutal** [pasdoc/pasdoc#49]
Testcase:
```
{ 
  @longcode(
  {$D+}
    Some long code
  )
}
unit foo;

interface

implementation

end.
```

**Comment by michaliskambi** [comment]
It's a more general bug: we do not support "nested comments" feature (from FPC). So PasDoc parser "sees" the following comment: 

```
{ 
  @longcode(
  {$D+}
```

... and then we try to parse the word `Some` as Pascal code.

The problem is not related to `@longCode` that handles compiler directives OK, e.g. this works OK:

```
(*
  @longcode(
  {$D+}
    Some long code
  )
*)
unit foo;

interface

implementation

end.
```

Note that Delphi doesn't support "nested comments" either, as far as I know (I'm on Linux right now with only FPC), according to e.g. https://stackoverflow.com/a/3843830 . So PasDoc parser is consistent with Delphi here, as well as FPC in Delphi mode (`fpc -Mdelphi foo.pas` also fails to parse this).

**Comment by Fr0sT-Brutal** [comment]
>we do not support "nested comments" feature (from FPC)

Oh, that's true! It's so easy to forget about capabilities of other IDEs/compilers/OS-es when you test with only one tool set :)
Sure, current parser behavior is consistent so it's not an issue. Including a code with compiler directives could be done with another comment style (luckily Pascal has plenty) or with external file. So I guess we can close this report.
