### ISSUE TITLE
[suggestion] Multiline tag parameters without parenthesis

### ISSUE THREAD

**Issue by Fr0sT-Brutal** [pasdoc/pasdoc#52]
Tags without parenthesis are cool but they only could have single-line parameter. I'd like to expand that to multiline.
I see two options:
* Using "line feed" character like `\` (like in shell scripts, C and so on)
  - Pros: well-known scheme
  - Cons: one will have to add this char for every line in parameter
```
@param some \
  long \
  text
```

* Read until next `@`
  - Pros: it will look very nice for arguments/returns/raises of a method, no any excess character.
  - Cons: when a multiline tag is followed by plain text, weird single `@` would be required.
```
@param some
  long
  text
@param some
  long
  text #2
```
```
@param some
  long
  text@
Plain text goes here
```

Opinions?

P.S. Instead of single `@` a `@br` tag could be required. So the parser will sure any multiline parameter ends with a tag.

**Comment by michaliskambi** [comment]
> Read until next @

This approach would result in surprising behavior when someone uses `@` for some "inline" ("inline" in terms of HTML) tag, that can be part of content, e.g.

```
@param Foo Use this parameter to do something @bold(important)!
```

Or

```
@unorderedList(
  @item Something @bold(important)!
)
```

Also, it breaks compatibility (many people would need to fix their existing comments). So we would have to make it "disabled by default" and only activated by some command-line option.

> Using "line feed" character like \ 

This approach looks safer to me (very small chance to break existing code, as people probably do not use `\` at end of line now, at least not often -- so we could have it "enabled by default", possibly no need to even add command-line option to disable).

So I would choose this approach. I know it looks a bit worse (instead of typing `(` and `)` (saving 2 characters) you will type 1 or more `\` characters). But it seems safer.

**Comment by Fr0sT-Brutal** [comment]
Agreed, sounds reasonable.

**Comment by Fr0sT-Brutal** [comment]
Closing as implemented
