### ISSUE TITLE
[feature, WIP] Parse implementation section

### ISSUE THREAD

**Issue by Fr0sT-Brutal** [pasdoc/pasdoc#61]
As described [here](https://github.com/pasdoc/pasdoc/wiki/WantedFeaturesParsingImplementation).
WIP in branch [feat_parse-impl](https://github.com/Fr0sT-Brutal/pasdoc/tree/feat_parse-impl)

Checklist:
- [x] Support standalone routines (done incl. any nesting level)
- [x] Support record/class members (done incl. any nesting level)
- [x] Decide what to do with overloads (done for now with index-based solution. In the future this should be solved adding parameter types to names and/or grouping)
- [x] Run current parsing code with lots of real units (done with several testcase fixes, merge mode "join" produces the same output as without new changes)
- [x] Add command line option
- [x] Add docs

(optional)
- [ ] Maybe parse internal items as well and add them with a special flag similar to visibility
Pros: ability to generate "advanced" or "developer" docs
Cons:
  - lots of work
  - lots of unwanted stuff in output - better to have ability to specify members that shall go to docs,  something like a new tag `@internal`.
- [x] Support back comments to allow description after method header (like in VTV)
- [ ] Add tags for making "virtual" descriptions that are not tied to real declaration, to place long descriptions in impl section and keep intf section clean.  Something like `@describe (TClass long long text)`. Only necessary for classes/records and their properties.

**Comment by michaliskambi** [comment]
Cool, I''ll try look at the branch this weekend. 

As for overloads: 

The problem with overloads is already present when parsing interface section. We indeed don't have a good solution for this in PasDoc now. Within this issue (parsing implementation) I propose we leave this as it is -- which means that 
- overloaded routines are parsed, 
- each overloaded version can have it's own description, 
- and links to overloaded routines are unfortunately bad (because all overloaded versions share the same anchor name in HTML documentation).

My preferred solution is a bit complicated:

- Parse routine parameters, and allow to use parameters in `@link`, so that `@link(Foo(Integer))` and `@link(Foo(String))` would work (assuming you have a procedure `Foo` with two overloads, one takes Integer the other one String).

    In this case, `@link(Foo)` should still be allowed (for backward compatibility and for people who use grouping, see below). It can lead to any version.

- Allow to group overloads (thus all overloads would have the same description), but make it optional, with `--group-overloads`. Or maybe automatically make a group, if only one overload in the namespace (like unit or class) has a description? I would be OK with automatic detection of it.

The display for the group in HTML should show them all overloads within one "box". I want to use the same display as I plan for stuff grouped by planned `@groupBegin` / `@groupEnd` tags. My plan for groups is on https://github.com/pasdoc/pasdoc/wiki/MichalisKamburelis , see section " Support for groups of items" there.

**Comment by Fr0sT-Brutal** [comment]
> Parse routine parameters, and allow to use parameters in @link, so that @link(Foo(Integer)) and @link(Foo(String)) would work (assuming you have a procedure Foo with two overloads, one takes Integer the other one String).

That would be awesome and bullet-proof, as it's the same logic that compilers use!

And I wait for grouping as well, I love to have things structured :)

Meanwhile I tend to implement an index-based logic: when `Foo` is encountered N-th time, an N-th entry with name `Foo` is searched. This would cover most of sane cases provided that methods are declared in the same order as defined (cases when one of overloads is ignored are not sane to me). This would require a change in getting an item from list though as currently `FindItem` always returns the first one.

**Comment by Fr0sT-Brutal** [comment]
Index-based solution of overloads is ready

**Comment by Fr0sT-Brutal** [comment]
Command-line option implemented

[Wiki page](https://github.com/Fr0sT-Brutal/pasdoc/wiki/ImplMergeModeOption) added

**Comment by michaliskambi** [comment]
1. I would prefer to avoid abbrevations in the command-line options. Instead of `--impl-merge-mode` I would prefer `--implementation-comments`, with values described like that:

    * `ignore` - Behave as by default: implementation comments are ignored.

    * `join` - Read both interface and implementation comments, and concatenate them. The concatenation process is smart: if the interface comment is also present (repeated) at the beginning of the implementation comment, then it will be ignored (to not repeat 2x the same text in the concatenated result).

    * `prefer-interface` - Read both interface and implementation comments. Use whichever comment is non-empty. If they are both non-empty, use the interface comment.

    * `prefer-implementation` - Just like `prefer-interface`, but if both comments are non-empty, use the implementation comment.

    I know it looks more verbose than what you propose, but also seems more obvious. E.g. `--implementation-comments=join` seems more obvious.

2. You write _Used units are concatenated always in the same way._ on https://github.com/Fr0sT-Brutal/pasdoc/wiki/ImplMergeModeOption . I am not sure what does this mean, what is the current treatment of the used units (`uses xxx` clause in the implementation section) in your branch?

    I think that they should be _ignored_ (I mean, they should not influence the output), regardless of the `--impl-merge-mode` / `--implementation-comments` value. The reason is that these units should not matter for the user of the unit. Since we display declarations from the `interface` section, so only the units used in the interface section of the unit should be visible in the "Used Units" output of PasDoc.

    For example consider this (from my https://castle-engine.io/modern_pascal_introduction.html#_qualifying_identifiers_with_unit_name ):


    ```pascal
    {$mode objfpc}{$H+}{$J-}
    unit UnitUsingColors;

    interface

    uses Graphics;

    procedure ShowColor(const Color: TColor);

    implementation

    uses GoogleMapsEngine;

    procedure ShowColor(const Color: Graphics.TColor);
    begin
      // WriteLn(ColorToString(Color));
    end;

    end.
    ```

    PasDoc shows declaration `procedure ShowColor(const Color: TColor)`. So it should also show _"Used Units: Graphics"_. Showing _"Used Units: Graphics, GoogleMapsEngine"_ would mislead user into thinking that `TColor` is the one defined in `GoogleMapsEngine` unit.

    I know, it's a rare edge-case :) I welcome other opinions :)

**Comment by Fr0sT-Brutal** [comment]
1. No problem! I've no strong position on naming, moreover I myself don't like my variants much. Though shortness is more convenient, full words are consistent to other options so I'm totally OK with renaming.
2. Umm, doesn't have a concrete opinion on this either and I've never used this option :) my logic was to show any used unit because many people like to move down as much units as possible for a reason that's totally unclear to me.
AFAIU the purpose of this option is mainly to grab links to units which will be in the output as well. From this POV adding impl section units is excess (currently impl-only items are ignored => nothing to link to). Anyway this very case is just a one line. I'll comment it out for now, maybe later things will change and it becomes useful

**Comment by Fr0sT-Brutal** [comment]
*phew* Implemented!
