### ISSUE TITLE
Make @code rejecting tags inside similar to @longcode

### ISSUE THREAD

**Issue by Fr0sT-Brutal** [pasdoc/pasdoc#66]
I guess there's no sense in having tags inside @code, isn't it? Now this causes unneeded markdown formatting,
```
`DO_SMTH_BAD`
```
turns to
'DO*SMTH*BAD'

**Comment by michaliskambi** [comment]
We want to allow tags in `@code`. E.g. you can use `@code(@link(MyFunction) := something)`. Our `@code` is similar to HTML `<code>`, it's not really specific to Pascal (I know, it''s inconsistent with `@longCode` :) ), it makes sense to use some formatting inside.

Maybe Markdown should be improved here, to not detect _ in the middle of words? On GitHub:

The underscores here do nothing special: DO_SMTH_BAD

The underscores here cause italic: _FOO_ and also _FOO_BAR_ (italic ends here).

Source:

```
The underscores here do nothing special: DO_SMTH_BAD

The underscores here cause italic: _FOO_ and also _FOO_BAR_ (italic ends here).
```

**Comment by Fr0sT-Brutal** [comment]
Well, I see the point in allowing links inside @code (I use it myself, nice). But what about other tags?
Or, as another option I could turn off all markdown inside @code - it's what I intended initially. Anyway there should be a way to write `A=B*C*D` and get expected results. What do you think?
As for special processing of underscores, hmm... funny. I didn't know that. I'll see if this could be done.

**Comment by michaliskambi** [comment]
I'm somewhat reluctant to add special exceptions to specific tags (e.g. "`@code` doesn't accept some tags", or "`@code` doesn't allow Markdown"). My thoughts:

- Just like in HTML `<code>` you can place any other inline stuff. 

- Making parts of the code bold makes sense (esp. since we don't do syntax highlighting for `@code`, as we don't assume it's Pascal). Some non-exhaustive list of tags that make sense in `@code`: `@bold`, `@italic`, `@link`, `@html`  / `@latex`, `@name`, `@className` ... 

- Introducing special rules to how `@code` (or other specific tags) are handled (e.g. to allow only some `@` tags, or disable Markdown) complicates our job. It complicates the implementation as well as the documentation.

- At the same time, I see your point of course. Testing, `A * B * C` (with spaces) looks OK in GitHub Markdown, but `A*B*C` (without spaces) makes the B italic. One has to write `A\*B*C` to avoid interpreting  the first asterisk as a beginning of bold.

- Another example is Markdown syntax itself. In Markdown, between backticks, other Markdown formatting doesn't work. E.g. `This *is not italic* even though it is surrounded by asterisks`. So clearly there is an example of language that decided to disable Markdown in some specific situations: Markdown itself :)

My suggested way forward would be:

1. Improve Markdown first (to detect underscores following similar specification at Github-flavored Markdown). Maybe look at other small inline features -- do we treat asterisks the same as Github Markdown? Maybe add support for "escaping" by backslash too?

2. Then let's test it on "real-life" examples. I'll turn "on" Markdown on https://castle-engine.io/apidoc-unstable/html/ at some point, and log where was the Markdown detected. Then we can judge whether it's more help, or nuisance, and how to deal with it :) If it's a nuisance, then indeed we could disable Markdown in `@code`. But first let's test more :)

**Comment by Fr0sT-Brutal** [comment]
You're right as usual ;) I've pushed changes that add some brain to md parsing
