### ISSUE TITLE
Uses not handle correctly

### ISSUE THREAD

**Issue by jdelauney** [pasdoc/pasdoc#74]
Hi in this sample 
```
uses
  Classes, SysUtils, fileutil, LazUtf8, lazfileutils, DateUtils,
  LCLIntf, LCLType,
  {$IFDEF Windows}
   Windows, GetText
  {$ENDIF}
  {$IFDEF UNIX}
   BaseUnix, Unix, Unixutil, linux
    {$IFDEF X11_SUPPORT}
     ,xlib
    {$ENDIF}
    {$IFDEF LCLCarbon}
     MacOSAll
    {$ENDIF}
  {$ENDIF};  
```
pasdoc return this 

> Entering interface section of unit BZSystem
> $IFDEF encountered (Windows), condition is 0, level 0
> SkipUntilElseOrFound: encountered directive ENDIF
> Skipped code, last directive is ENDIF
> $IFDEF encountered (UNIX), condition is 0, level 0
> SkipUntilElseOrFound: encountered directive IFDEF
> SkipUntilElseOrFound: encountered directive ENDIF
> SkipUntilElseOrFound: encountered directive IFDEF
> SkipUntilElseOrFound: encountered directive ENDIF
> SkipUntilElseOrFound: encountered directive ENDIF
> Skipped code, last directive is ENDIF
> Error EPasDoc: H:\...\BZSystem.pas(58): identifier expected but symbol ";" found while parsing unit BZSystem.pas, continuing...

it seem that the nested IFDEF in UNIX part are not handle  correctly

Best regards

**Comment by jdelauney** [comment]
if this can help you, if i do

```
uses
  Classes, SysUtils, fileutil, LazUtf8, lazfileutils, DateUtils,
  LCLIntf, LCLType,
  {$IFDEF Windows}
   Windows, GetText;
  {$ENDIF}
  //{$IFDEF UNIX}
  // BaseUnix, Unix, Unixutil, linux
  //  {$IFDEF X11_SUPPORT}
  //   ,xlib
  //  {$ENDIF}
  //  {$IFDEF LCLCarbon}
  //   MacOSAll
  //  {$ENDIF}
  //{$ENDIF}; 
```
pasdoc return : 

`Error EPasDoc: H:\...\BZSystem.pas(63): identifier expected but reserved word "const" found while parsing unit BZSystem.pas, continuing...`

And if i just do

```
uses
  Classes, SysUtils, fileutil, LazUtf8, lazfileutils, DateUtils,
  LCLIntf, LCLType,
  {$IFDEF Windows}
   Windows, GetText
  {$ENDIF};
```
Same error as first

> Error EPasDoc: H:...\BZSystem.pas(58): identifier expected but symbol ";" found while parsing unit

or

```
uses
  Classes, SysUtils, fileutil, LazUtf8, lazfileutils, DateUtils,
  LCLIntf, LCLType,
  {$IFDEF Windows}
   Windows, GetText;
  {$ENDIF}
```
same result :

> Error EPasDoc: H:\...\BZSystem.pas(63): identifier expected but reserved word "const" found while parsing unit BZSystem.pas, continuing...`


Cheers

**Comment by jdelauney** [comment]
It's very strange in another unit i have :
```
//==============================================================================
{$mode objfpc}{$H+}
{$i ..\bzscene_options.inc}
//==============================================================================

interface

uses
  Classes, SysUtils, LCLIntf, LCLType
  {$IFDEF WINDOWS}
  ,windows
  {$ENDIF}
  {$IFDEF UNIX}
  ,BaseUnix
  {$ENDIF};
```

And all work fine.

For info, all of my units have the same template header , so...????

Cheers

**Comment by michaliskambi** [comment]
Unlike compiler, PasDoc *does not* define any standard conditional compilation symbols. See docs on https://github.com/pasdoc/pasdoc/wiki/ConditionalDefines .

This means that even if you run PasDoc on Windows, the symbol `WINDOWS` is not defined. The reason is that (unlike compiler, which produces executable for given platform) PasDoc prepares docs that you usually want to be cross-platform. So it's up to you to decide what symbols best accomplish this. This is explained in https://github.com/pasdoc/pasdoc/wiki/ConditionalDefines , in particular see the section "Make sure the resulting code is valid" there.

So: use appropriate `--define` and/or `--conditionals` command-line option.

So your first example, for PasDoc (when neither `WINDOWS` nor `UNIX` are defined) is equivalent to this:

```
uses
  Classes, SysUtils, fileutil, LazUtf8, lazfileutils, DateUtils,
  LCLIntf, LCLType,
; 
```

-> so you have a "dangling" comma, which is what PasDoc is complaining about.

This explains the rest of your symptoms too. 

E.g.

```
uses
  Classes, SysUtils, fileutil, LazUtf8, lazfileutils, DateUtils,
  LCLIntf, LCLType,
  {$IFDEF Windows}
   Windows, GetText;
  {$ENDIF}
  //{$IFDEF UNIX}
  // BaseUnix, Unix, Unixutil, linux
  //  {$IFDEF X11_SUPPORT}
  //   ,xlib
  //  {$ENDIF}
  //  {$IFDEF LCLCarbon}
  //   MacOSAll
  //  {$ENDIF}
  //{$ENDIF}; 
```

-> this is for PasDoc an unterminated uses clause:

```
uses
  Classes, SysUtils, fileutil, LazUtf8, lazfileutils, DateUtils,
  LCLIntf, LCLType,
```

.. so PasDoc tries to parse the rest of the `uses` clause, and it seems encounters `const` in your unit.

Your final example works OK, because you have moved the comma into ifdef sections:

```
uses
  Classes, SysUtils, LCLIntf, LCLType
  {$IFDEF WINDOWS}
  ,windows
  {$ENDIF}
  {$IFDEF UNIX}
  ,BaseUnix
  {$ENDIF};
```

-> is seen as (valid)

```
uses
  Classes, SysUtils, LCLIntf, LCLType
;
```

**Comment by Fr0sT-Brutal** [comment]
I'll add that running PasDoc without any conditional being set is a good method to check correctness. F.ex., your 1st example will fail being compiled for, say, DOS (let's imagine such situation...). While this could be intentional as you don't assume your unit supports these platforms PasDoc won't process this construction. You can fix this either with setting proper defines (in some cases even multiple platforms at the same time) or modify your code to be semantically correct under ALL conditions. `$message fatal '...'` is great for this purpose. I already changed some fragments in my code from trivial
```
{$IF OldCompiler} Ancient stuff is not supported {$ENDIF}
```
to
```
{$IF OldCompiler} {$MESSAGE FATAL 'Ancient stuff is not supported'} {$ENDIF}
```
to make PasDoc happy.

**Comment by jdelauney** [comment]
Oh ! Oh ! Oh ! i 'm apologize, i don't take care of the place where the commas are, in my first sample, usually i never place comma at end like this, huch !! sorry ;)

Thanks for the tipFr0sT-Brutal 👍
