### ISSUE TITLE
[FEATURE REQUEST] Markdown support

### ISSUE THREAD

**Issue by silvioprog** [pasdoc/pasdoc#9]
Hello buddies.

What do you think about to support Markdown in PasDoc? Markdown is present in many other documenting tools (Github wiki/docs/blogs, Doxygen, JavaDoc, VSdocman etc.).

Thank you!

**Comment by michaliskambi** [comment]
We very much want Markdown support:) Preferably following the specification like https://github.github.com/gfm/ (otherwise, just saying "Markdown" is little ambiguous, some pecularities of syntax are different across implementations).

**Comment by silvioprog** [comment]
Awesome! Do you know any Delphi/FPC component to processing Markdown as GFM Spec?

**Comment by michaliskambi** [comment]
There is https://github.com/grahamegrieve/delphi-markdown . I have not yet done testing, or extensive search for it. And we will need something that works with both FPC and Delphi. (Or, eventually, at least only FPC -- as that's what I use to compile PasDoc for all the platforms.)

**Comment by Fr0sT-Brutal** [comment]
I made basic support of bold, italic, inline code and long code [here](https://github.com/Fr0sT-Brutal/pasdoc/tree/feat_markdown). Not sure I plugged it correctly though. I just extended `TTagManager.CoreExecute` so that it treats markdown blocks as usual tags. Behavior is optional and controlled by command-line option `use-markdown`

**Comment by michaliskambi** [comment]
@Fr0sT-Brutal Awesome! I'll review your 2 PRs and 1 bugreport this weekend, thank you!

At first glance, the approach from https://github.com/Fr0sT-Brutal/pasdoc/commits/feat_markdown is cool for me. I would slightly prefer to use some ready Markdown-processing library (this way the solution would "scale" to all Markdown syntax), but I understand that no such library exists for both FPC and Delphi? Did you look at https://github.com/grahamegrieve/delphi-markdown -- I didn't check it with FPC myself?

**Comment by Fr0sT-Brutal** [comment]
@michaliskambi I'm the first to use already written libs instead of writing primitive things from scratch.
But - there's two places to plug in a markdown handler:

- Parsing stage. This is where I plugged into. This way we got the context and use all existing abilities of PasDoc tags. Alas, if we use external lib here we'll get just formatted HTML. This will be actual for HTML output formats only (not XML/Latex). Ideally we need an external lib to generate abstract syntax tree. I took a quick look at d-md lib and didn't find it could do what we need.
- Formatting stage. It's just like `html := FormatHTML(FormatMarkdown(Comment))`. Could be useful but it needs to know context (to skip contents of `@code`, f.ex.) and it won't produce XML/Latex output as well.

Moreover, not much markdown abilities are useful and applicable to PasDoc IMHO. I have only links `[Foo](example.com)` and numbered/bullet lists in mind; probably some kind of simple ASCII tables. 

Probably we could add special `@markdown` tag similar to `@html` to have full markdown power; maybe it's good example for making a plugin.

**Comment by michaliskambi** [comment]
@Fr0sT-Brutal ACK. I think you plugged at the correct place in https://github.com/Fr0sT-Brutal/pasdoc/commits/feat_markdown , so I like your approach. I very like how your change in https://github.com/Fr0sT-Brutal/pasdoc/commit/b6e0d4b0e2bfdeac2becfbfce24979251b68421f makes only a local modification to the existing code (calling `FindMarkdownTag` when necessary). This looks maintainable. Current logic in `PasDoc_TagManager.pas` is quite complicated so I am careful when changing stuff there :)

Indeed external library would have to generate abstract tree as an output, so that we can use it for any PasDoc output -- HTML, LaTeX etc. So if there's no such library available, I'm cool with rolling our own solution.

For me (as PasDoc user), Markdown is most "crucial" for lists. This is my main problem with current lists tags ( https://github.com/pasdoc/pasdoc/wiki/ListTags ). I use them a lot, but the markup (all these `@unorderedList`, `@item` tags) makes it hard to read when looking at Pascal code.

Summary:

- I like your approach. Feel free to submit PR with https://github.com/Fr0sT-Brutal/pasdoc/commits/feat_markdown now. 

- I would change `--use-markdown` to just `--markdown` (and so all identifiers `UseMarkdown` to `Markdown`), otherwise I'm cool with everything in your PR. (I know, it's consistent with `--use-tipue-search`, but I would change it to just `--tipue-search` if I would implement it today :) ).

- I would be very happy if you could implement Markdown for lists too. This is one of my personal "very desired" features.

Thank you for your work!

**Comment by Fr0sT-Brutal** [comment]
@michaliskambi yeah, syntax of lists is scary.
I changed option name to "markdown" as you suggested and implemented basic support of lists but nested lists not supported yet

**Comment by Fr0sT-Brutal** [comment]
Whooo... I think I did it!
Nested lists are not a trouble anymore

 - parent list item #5.1
   - nested list item #5.1.1
     - nested list item #5.1.1.1
       - nested list item #5.1.1.1.1
     - nested list item #5.1.1.2
   - nested list item #5.1.2

could be set by 
```
 - parent list item #5.1
   - nested list item #5.1.1
     - nested list item #5.1.1.1
       - nested list item #5.1.1.1.1
     - nested list item #5.1.1.2
   - nested list item #5.1.2
```

**Comment by michaliskambi** [comment]
Very nice work, thank you again  @Fr0sT-Brutal !  The PR https://github.com/pasdoc/pasdoc/pull/51 is merged, it's all documented on https://github.com/pasdoc/pasdoc/wiki/MarkdownOption .

I'm closing this issue. A new PasDoc build with it should be available shortly on http://michalis.ii.uni.wroc.pl/pasdoc-snapshots/ of course.

Not 100% of Markdown is implemented, but we can make separate bugreports/PRs for them :)

**Comment by michaliskambi** [comment]
P.S. Note that I'm OK with *some* breaking of compatibility of Markdown syntax in next PRs, as long as the new version is better/closer to what GutHub supports and https://github.github.com/gfm/ specifies. E.g. right now

```
- list item #1.1
- list item #1.2

  - list item #2.1
  - list item #2.2
```

... makes four equally-indented list items in PasDoc, while in GitHub it will turn the last 2 items into a nested list (IOW, paragraph break doesn't stop the list on GitHub). Changing this would be OK.

**Comment by Fr0sT-Brutal** [comment]
Well, that would require more complex list detection logic - now it's pretty simple "from what looks like a list item 'til first empty line". I'm OK as well if anyone does this but unlikely that anyone will be me xDDD
