### ISSUE TITLE
Set new forum for PasDoc developers

### ISSUE THREAD

**Issue by michaliskambi** [pasdoc/pasdoc#91]
@silvioprog @Fr0sT-Brutal @PifPof73 and everyone else interested:

I see that we have a renewed interest in PasDoc, with people trying out and wanting to contribute PasDoc. This makes me very happy :) All contributions are welcome. This project is alive because of *many* people who have been active throughout the years :)

I want to communicate some things:

1. I want to create a good place to communicate for us all. I'll setup a Discourse forum for PasDoc soon.

    I have a good experience with Discourse at my other project Castle Game Engine. [Castle Game Engine forum](https://forum.castle-engine.io/) works and looks nicely, and it's relatively trivial to maintain.

    In the past we had a mailing list -- but it was less and less used. I guess people are less used to communicating this way (even though I think mailing lists rule :) ). For some projects, an instant communication (like Freenode or Slack or Discord) also works cool. I want to choose just *one* communication channel for the beginning, and from my observation "forum" is a choice that satisfies most people :) 

    Comments are welcome -- I want a place where we communicate, not a place that lies ignored :) So if e.g. nobody likes forums, and everyone would instead prefer a Freenode (IRC) place -- we will do it. 

2. Some introduction about myself: Most of my life time now is spend on [Castle Game Engine](https://castle-engine.io/) where I use PasDoc for [Castle Game Engine API Documentation](https://castle-engine.io/apidoc-unstable/html/index.html). So I have a lot of interest in keeping PasDoc alive :)

3. As I see that people look at [PasDoc issues on GitHub](https://github.com/pasdoc/pasdoc/issues) as a list of potential tasks to implement, I added there most important TODOs from myself :) Some of them are hard and large tasks, some are small. I just wanted to give you a sense of direction, what features I personally consider important. 

    My personal preference is issue https://github.com/pasdoc/pasdoc/issues/85 , which should result in simpler, mobile-friendly, HTML default look, based on Bootstrap. I consider this task so important that I'd be willing to mark next PasDoc version as `1.0.0` after finishing this :)

Any comments are welcome. Until I setup this forum, please feel welcome to just comment in this GitHub issue :)

**Comment by michaliskambi** [comment]
Oh, and (adding to point 3 above) you may look at the [Castle Game Engine Trello board titles "PasDoc (Features important for CGE)"](https://trello.com/b/W1WeyREa/pasdoc-features-important-for-cge). These are PasDoc features most "desired" by Castle Game Engine. There are just 2 tickets there, 
- HTML 5 with Bootstrap output
- `@groupBegin` / `@groupEnd` support

**Comment by silvioprog** [comment]
- ([other reference](https://help.github.com/en/github/building-a-strong-community/about-team-discussions))

**Comment by PifPof73** [comment]
Hi all,
I just dived in last week without introducing myself.
I am working as head of a small IT - department (with me 5 people) and inherit a Delphi rich database application a few years ago.
As I had to work myself into a huge (and almost non documented) source I was searching for a autodoc tool, to get at least a good overview over the project.
I knew doxygen from old ANSI - C - projects (yes, I am an old man ... the _73_ in my nick is the year of birth), so I was quiet happy to find pasdoc and I'm using it since 2012.

During Covid-19 lock-down I am sitting in my home office and do things, that normally lying there with no time - like _documentation_  8o) .
I remembered pasdoc as I wanted to update my source docs and thought, I should give something back as I use this nice tool, saving some hours of hard reverse engineering.

So here I am, general I know how to read and write code, today I mainly use Python3, in the past I coded C, C++, VB and inherited Pascal (Delphi).
I am no web designer, so my knowledge of html and css is quite basic, so please be patient if you expect formatting the output from me :).

To be honest, it's my first project collaborating on github, so please be patient with me doing stupid things with pull requests, commits, etc.
Until know I was a one-man show using git just locally for myself.
This is quite a learning curve for me and I'm happy that you all welcome me, be patient and give me some advise and tips.

At home I am using delphi in a virtual Windows VM on Mac OSX Catalina.
If you are interested, we could discuss to port pasdoc also to Apple - but I thing we should compile a 64bit version for Windows first.
Or I could try to compile it with FreePascal directly with XCode (but this is new land for me).
Is there any interest in this direction?

Cheers,
PifPof73

**Comment by michaliskambi** [comment]
@PifPof73 Welcome! :)

As for platforms - we already support 64-bit versions of Windows, they are even automatically build for https://michalis.ii.uni.wroc.pl/pasdoc-snapshots/ . We also support macOS. The console version of PasDoc should just work on latest macOS (including 64-bit only macOS Catalina).

The GUI version for macOS Catalina is something  we want indeed. It should be just a matter of using latest Lazarus to compile pasdoc_gui with Cocoa widgetset. So it's mainly a matter of testing:) If you are interested in doing this testing, just grab latest FPC and Lazarus and compile pasdoc_gui and check how does it work.

**Comment by PifPof73** [comment]
Hi @michaliskambi,
I installed Lazarus on my Mac Os Catalina (which is not so easy like it should ;)) and was able to compile the gui project.
The gui lookes identically to the delphi gui - there are some deprecation warnings, but I was able to use it and generate a doc of the project itself.
If you wish I can start to check the deprecation warnings and find out how to get rid of them.
And I can provide screenshots of the gui under MacOsX if you want - then I need the info in which format and where to post.
Regards,
PifPof73

**Comment by Fr0sT-Brutal** [comment]
+1 for the forum, I prefer it for tech subjects over old-school mail list; however, GH conversations that silvioprog mentioned seem a good start point while the number of team members is low.

**Comment by michaliskambi** [comment]
@PifPof73 Thanks for testing on macOS. If you have some deprecation warnings from `pasdoc_gui`, indeed I'm interested in fixing them. I'm curious what they are -- the LCL API is the same on macOS, and I don't see any warning when compiling `pasodc_gui` on Linux now.

Note that the `delphi_gui` isn't developed anymore. It serves as a test that PasDoc as a component works in Delphi too, but in practice `pasdoc_gui` (using Lazarus) is developed more and has more features.

**Comment by michaliskambi** [comment]
Indeed the "team discussions" posted by @silvioprog seem like a best option -- essentially a simple forum given for us by GitHub, so it's definitely simplest to set up and use for now :)

I created a "Developers" team on https://github.com/orgs/pasdoc/teams/developers , and you're all invited there and use it for any talking related to this project :) The link to it is also in our [wiki main page](https://github.com/pasdoc/pasdoc/wiki) in the "Get Involved" section. Let's see how this works.
